# fly.toml app configuration file generated for replyflow on 2026-02-27T01:29:49-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "replyflow"
primary_region = "gru"
kill_signal = "SIGTERM"
kill_timeout = 30
swap_size_mb = 512

[env]
  DATABASE_PATH = "/data/gitjobs.db"
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

  [[http_service.checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "60s"
    method = "GET"
    path = "/api/health"
    headers = { X-Forwarded-Proto = "https" }

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"

[[mounts]]
  source = "replyflow_data"
  destination = "/data"
